In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 5GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/pitchers/pitching.csv
/kaggle/input/baseball-databank/SeriesPost.csv
/kaggle/input/baseball-databank/AwardsPlayers.csv
/kaggle/input/baseball-databank/Pitching.csv
/kaggle/input/baseball-databank/AllstarFull.csv
/kaggle/input/baseball-databank/TeamsFranchises.csv
/kaggle/input/baseball-databank/AwardsShareManagers.csv
/kaggle/input/baseball-databank/FieldingOF.csv
/kaggle/input/baseball-databank/Master.csv
/kaggle/input/baseball-databank/Managers.csv
/kaggle/input/baseball-databank/Teams.csv
/kaggle/input/baseball-databank/BattingPost.csv
/kaggle/input/baseball-databank/AwardsManagers.csv
/kaggle/input/baseball-databank/ManagersHalf.csv
/kaggle/input/baseball-databank/PitchingPost.csv
/kaggle/input/baseball-databank/Salaries.csv
/kaggle/input/baseball-databank/HallOfFame.csv
/kaggle/input/baseball-databank/Fielding.csv
/kaggle/input/baseball-databank/TeamsHalf.csv
/kaggle/input/baseball-databank/AwardsSharePlayers.csv
/kaggle/input/baseball-databank/Batting.csv

In [2]:
pitching=pd.read_csv('/kaggle/input/pitchers/pitching.csv').drop(columns='Unnamed: 0')
pitching

,playerID,stint,W,L,G,GS,CG,SHO,SV,H,...,WP,HBP,BK,BFP,GF,R,SH,SF,GIDP,IP
0,newsobo01,39.0,211.0,222.0,600.0,483.0,246.0,31.0,21.0,3769.0,...,60.0,61.0,7.0,16467.0,71.0,1908.0,0.0,0.0,0.0,3759.333333
1,johnto01,30.0,288.0,231.0,760.0,700.0,162.0,46.0,4.0,4783.0,...,187.0,98.0,16.0,19692.0,22.0,2017.0,0.0,0.0,0.0,4710.333333
2,kaatji01,31.0,283.0,237.0,898.0,625.0,180.0,31.0,18.0,4620.0,...,128.0,122.0,6.0,19021.0,102.0,2038.0,0.0,0.0,0.0,4530.333333
3,ryanno01,27.0,324.0,292.0,807.0,773.0,222.0,61.0,3.0,3923.0,...,277.0,158.0,33.0,22575.0,13.0,2178.0,0.0,0.0,0.0,5386.000000
4,carltst01,31.0,329.0,244.0,741.0,709.0,254.0,55.0,2.0,4672.0,...,183.0,53.0,90.0,21683.0,13.0,2130.0,0.0,0.0,0.0,5217.333333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,beggsjo01,11.0,48.0,35.0,238.0,41.0,23.0,4.0,29.0,688.0,...,4.0,4.0,3.0,2895.0,127.0,284.0,0.0,0.0,0.0,693.666667
1458,tallebr01,11.0,16.0,25.0,242.0,36.0,0.0,0.0,0.0,459.0,...,6.0,25.0,1.0,2040.0,51.0,264.0,9.0,23.0,0.0,460.000000
1459,augusje01,10.0,55.0,59.0,279.0,104.0,27.0,6.0,11.0,1028.0,...,21.0,20.0,4.0,4101.0,75.0,491.0,0.0,0.0,0.0,944.000000
1460,barnevi01,11.0,61.0,59.0,205.0,135.0,58.0,7.0,11.0,1192.0,...,9.0,8.0,1.0,4643.0,31.0,525.0,0.0,0.0,0.0,1094.000000
1461,burketi01,12.0,49.0,33.0,498.0,2.0,0.0,0.0,102.0,624.0,...,25.0,21.0,2.0,2906.0,262.0,251.0,0.0,0.0,0.0,699.333333

In [3]:
hof=pd.read_csv('/kaggle/input/baseball-databank/HallOfFame.csv')
hof

,playerID,yearid,votedBy,ballots,needed,votes,inducted,category,needed_note
0,cobbty01,1936,BBWAA,226.0,170.0,222.0,Y,Player,NaN
1,ruthba01,1936,BBWAA,226.0,170.0,215.0,Y,Player,NaN
2,wagneho01,1936,BBWAA,226.0,170.0,215.0,Y,Player,NaN
3,mathech01,1936,BBWAA,226.0,170.0,205.0,Y,Player,NaN
4,johnswa01,1936,BBWAA,226.0,170.0,189.0,Y,Player,NaN
...,...,...,...,...,...,...,...,...,...
4115,grudzma01,2016,BBWAA,440.0,330.0,0.0,N,Player,NaN
4116,ausmubr01,2016,BBWAA,440.0,330.0,0.0,N,Player,NaN
4117,hamptmi01,2016,BBWAA,440.0,330.0,0.0,N,Player,NaN
4118,castilu01,2016,BBWAA,440.0,330.0,0.0,N,Player,NaN
4119,lowelmi01,2016,BBWAA,440.0,330.0,0.0,N,Player,NaN

In [4]:
hof=hof[hof['category'].isin(['Player'])]
hof=hof.drop(columns=['needed_note'])
hof['percent']=hof['votes']/hof['ballots']
hof['threshold']=hof['needed']/hof['ballots']
hof

,playerID,yearid,votedBy,ballots,needed,votes,inducted,category,percent,threshold
0,cobbty01,1936,BBWAA,226.0,170.0,222.0,Y,Player,0.982301,0.752212
1,ruthba01,1936,BBWAA,226.0,170.0,215.0,Y,Player,0.951327,0.752212
2,wagneho01,1936,BBWAA,226.0,170.0,215.0,Y,Player,0.951327,0.752212
3,mathech01,1936,BBWAA,226.0,170.0,205.0,Y,Player,0.907080,0.752212
4,johnswa01,1936,BBWAA,226.0,170.0,189.0,Y,Player,0.836283,0.752212
...,...,...,...,...,...,...,...,...,...,...
4115,grudzma01,2016,BBWAA,440.0,330.0,0.0,N,Player,0.000000,0.750000
4116,ausmubr01,2016,BBWAA,440.0,330.0,0.0,N,Player,0.000000,0.750000
4117,hamptmi01,2016,BBWAA,440.0,330.0,0.0,N,Player,0.000000,0.750000
4118,castilu01,2016,BBWAA,440.0,330.0,0.0,N,Player,0.000000,0.750000
4119,lowelmi01,2016,BBWAA,440.0,330.0,0.0,N,Player,0.000000,0.750000

In [5]:
hof_clean=pd.DataFrame()
for player in hof['playerID'].value_counts().index:
    playerdf=pd.DataFrame()
    df=hof[hof['playerID'].isin([player])].reset_index()
    year=df.max()['yearid']
    attempts=len(df)
    if df['inducted'].str.contains('Y').any():
        inducted=df[df['inducted'].isin(['Y'])].reset_index()
        percent=inducted['percent'][0]
        threshold=inducted['threshold'][0]
        votedBy=inducted['votedBy'][0]
        playerdf=playerdf.append({'year':year,'playerID':player,'percent':percent,'threshold':
                                threshold,'years':attempts,'votedBy':votedBy,'inducted':'Y'},ignore_index=True)
    else:
        max_percent=df.max()['percent']
        threshold=df['threshold'][df['percent'].idxmax()]
        votedBy=df['votedBy'].value_counts().index[0]
        playerdf=playerdf.append({'year':year,'playerID':player,'percent':max_percent,'threshold':
                                threshold,'years':attempts,'votedBy':votedBy,'inducted':'N'},ignore_index=True)
    hof_clean=hof_clean.append(playerdf)

In [6]:
hof_clean

   inducted   percent   playerID  threshold   votedBy    year  years
0         Y       NaN  roushed01        NaN  Veterans  1962.0   20.0
0         Y       NaN  youngro01        NaN  Veterans  1972.0   19.0
0         Y  0.869281  ruffire01        NaN   Run Off  1967.0   18.0
0         Y       NaN  schalra01        NaN  Veterans  1955.0   18.0
0         Y       NaN  wilsoha01        NaN  Veterans  1979.0   17.0
..      ...       ...        ...        ...       ...     ...    ...
0         N  0.006757   dentbu01   0.750000     BBWAA  1990.0    1.0
0         N  0.012685  guerrpe01   0.750529     BBWAA  1998.0    1.0
0         N  0.076923  comisch01   0.756410  Veterans  1936.0    1.0
0         N  0.002237  tenacge01   0.751678     BBWAA  1989.0    1.0
0         N  0.000000  mcauldi01   0.750623     BBWAA  1981.0    1.0

[1189 rows x 7 columns]

In [7]:
combined=pitching.join(hof_clean.set_index('playerID'), on='playerID')
combined

,playerID,stint,W,L,G,GS,CG,SHO,SV,H,...,SH,SF,GIDP,IP,inducted,percent,threshold,votedBy,year,years
0,newsobo01,39.0,211.0,222.0,600.0,483.0,246.0,31.0,21.0,3769.0,...,0.0,0.0,0.0,3759.333333,N,0.094118,0.750000,BBWAA,1973.0,13.0
1,johnto01,30.0,288.0,231.0,760.0,700.0,162.0,46.0,4.0,4783.0,...,0.0,0.0,0.0,4710.333333,N,0.317254,0.751391,BBWAA,2009.0,15.0
2,kaatji01,31.0,283.0,237.0,898.0,625.0,180.0,31.0,18.0,4620.0,...,0.0,0.0,0.0,4530.333333,N,0.295508,0.751773,BBWAA,2003.0,15.0
3,ryanno01,27.0,324.0,292.0,807.0,773.0,222.0,61.0,3.0,3923.0,...,0.0,0.0,0.0,5386.000000,Y,0.987928,0.750503,BBWAA,1999.0,1.0
4,carltst01,31.0,329.0,244.0,741.0,709.0,254.0,55.0,2.0,4672.0,...,0.0,0.0,0.0,5217.333333,Y,0.956140,0.750000,BBWAA,1994.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1457,beggsjo01,11.0,48.0,35.0,238.0,41.0,23.0,4.0,29.0,688.0,...,0.0,0.0,0.0,693.666667,NaN,NaN,NaN,NaN,NaN,NaN
1458,tallebr01,11.0,16.0,25.0,242.0,36.0,0.0,0.0,0.0,459.0,...,9.0,23.0,0.0,460.000000,NaN,NaN,NaN,NaN,NaN,NaN
1459,augusje01,10.0,55.0,59.0,279.0,104.0,27.0,6.0,11.0,1028.0,...,0.0,0.0,0.0,944.000000,NaN,NaN,NaN,NaN,NaN,NaN
1460,barnevi01,11.0,61.0,59.0,205.0,135.0,58.0,7.0,11.0,1192.0,...,0.0,0.0,0.0,1094.000000,NaN,NaN,NaN,NaN,NaN,NaN
1461,burketi01,12.0,49.0,33.0,498.0,2.0,0.0,0.0,102.0,624.0,...,0.0,0.0,0.0,699.333333,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
clean=combined[-combined['inducted'].isnull()]
clean

,playerID,stint,W,L,G,GS,CG,SHO,SV,H,...,SH,SF,GIDP,IP,inducted,percent,threshold,votedBy,year,years
0,newsobo01,39.0,211.0,222.0,600.0,483.0,246.0,31.0,21.0,3769.0,...,0.0,0.0,0.0,3759.333333,N,0.094118,0.750000,BBWAA,1973.0,13.0
1,johnto01,30.0,288.0,231.0,760.0,700.0,162.0,46.0,4.0,4783.0,...,0.0,0.0,0.0,4710.333333,N,0.317254,0.751391,BBWAA,2009.0,15.0
2,kaatji01,31.0,283.0,237.0,898.0,625.0,180.0,31.0,18.0,4620.0,...,0.0,0.0,0.0,4530.333333,N,0.295508,0.751773,BBWAA,2003.0,15.0
3,ryanno01,27.0,324.0,292.0,807.0,773.0,222.0,61.0,3.0,3923.0,...,0.0,0.0,0.0,5386.000000,Y,0.987928,0.750503,BBWAA,1999.0,1.0
4,carltst01,31.0,329.0,244.0,741.0,709.0,254.0,55.0,2.0,4672.0,...,0.0,0.0,0.0,5217.333333,Y,0.956140,0.750000,BBWAA,1994.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1358,ruckena01,10.0,134.0,134.0,336.0,272.0,186.0,38.0,14.0,2089.0,...,0.0,0.0,0.0,2375.333333,N,0.064378,0.751073,BBWAA,1946.0,7.0
1363,whitewi01,10.0,229.0,166.0,403.0,401.0,394.0,36.0,0.0,3440.0,...,0.0,0.0,0.0,3542.666667,N,0.019337,0.751381,BBWAA,1977.0,3.0
1369,pearsmo01,10.0,100.0,61.0,224.0,191.0,94.0,5.0,4.0,1392.0,...,0.0,0.0,0.0,1429.666667,N,0.003759,0.751880,BBWAA,1958.0,1.0
1388,coaklan01,11.0,58.0,59.0,150.0,124.0,87.0,11.0,3.0,1021.0,...,0.0,0.0,0.0,1072.333333,N,0.003817,0.751908,BBWAA,1938.0,1.0
1454,groveor01,10.0,63.0,73.0,207.0,152.0,66.0,11.0,4.0,1237.0,...,0.0,0.0,0.0,1176.666667,N,0.026022,0.750929,BBWAA,1960.0,2.0

In [9]:
#see if any players need to be weeded out, those who pitched in less than 200 games
clean[clean['G']<200]

,playerID,stint,W,L,G,GS,CG,SHO,SV,H,...,SH,SF,GIDP,IP,inducted,percent,threshold,votedBy,year,years
1106,cadorle01,12.0,68.0,72.0,192.0,147.0,83.0,10.0,3.0,1273.0,...,0.0,0.0,0.0,1257.333333,N,0.008264,0.752066,BBWAA,1948.0,1.0
1228,ruthba01,10.0,94.0,46.0,163.0,148.0,107.0,17.0,4.0,974.0,...,0.0,0.0,0.0,1221.333333,Y,0.951327,0.752212,BBWAA,1936.0,1.0
1331,lockebo01,11.0,16.0,15.0,165.0,23.0,2.0,2.0,10.0,432.0,...,0.0,0.0,0.0,416.666667,N,0.000000,0.750623,BBWAA,1981.0,1.0
1388,coaklan01,11.0,58.0,59.0,150.0,124.0,87.0,11.0,3.0,1021.0,...,0.0,0.0,0.0,1072.333333,N,0.003817,0.751908,BBWAA,1938.0,1.0

Not really any hitters in this dataset. The one that stands out is Babe Ruth, who is obviously known for his hitting. However, he pitched a lot in his career, so let's leave him in here for now (he actually had the best ERA in the MLB for one year).

In [10]:
clean.to_csv('pitching2.csv')